import pytest
import os
import json
from unittest.mock import patch
from fastapi.testclient import TestClient
from exceptionos.api.main import app
from exceptionos.database import get_db, init_db
from exceptionos.database.models import Dataset, CaseRecord, AIInteraction
from exceptionos.ai.provider import ProviderException

client = TestClient(app)

@pytest.fixture(scope="module", autouse=True)
def setup_db():
    init_db()
    
@pytest.fixture
def test_dataset():
    db = next(get_db())
    dataset = Dataset(id="test-dataset-ai", name="Test AI Dataset", source_type="TEST")
    db.add(dataset)
    db.commit()
    
    case = CaseRecord(
        id="case-1",
        dataset_id=dataset.id,
        key="test-key",
        classification="amount_mismatch"
    )
    db.add(case)
    db.commit()
    
    yield dataset
    
    # Cleanup
    db.query(AIInteraction).delete()
    db.query(CaseRecord).filter(CaseRecord.dataset_id == dataset.id).delete()
    db.query(Dataset).filter(Dataset.id == dataset.id).delete()
    db.commit()
    db.close()

# Mock response for a valid response
def mock_generate_valid(*args, **kwargs):
    return json.dumps({
        "answer": "This is a valid answer.",
        "verified_facts": ["Fact 1"],
        "recommendations": ["Do this"],
        "confidence": 0.9,
        "sources": [{"type": "dataset", "id": "test"}]
    })

# Mock response for insufficient data generated by model
def mock_generate_insufficient(*args, **kwargs):
    return json.dumps({
        "error": "Insufficient data available for analysis..."
    })

# Mock response for plain text
def mock_generate_plaintext(*args, **kwargs):
    return "This is just some text the AI generated instead of JSON."

# Mock response for malformed JSON/missing fields
def mock_generate_malformed(*args, **kwargs):
    return json.dumps({
        "answer": "Missing other fields"
    })

def mock_generate_provider_failure(*args, **kwargs):
    raise ProviderException("Groq API rate limit exceeded")

def test_1_normal_valid_response(test_dataset):
    with patch('exceptionos.ai.provider.MockAIProvider.generate', side_effect=mock_generate_valid):
        os.environ["AI_PROVIDER"] = "mock"
        response = client.post("/api/copilot/chat", json={
            "message": "Analyze this",
            "dataset_id": test_dataset.id
        })
        assert response.status_code == 200
        data = response.json()
        assert data["response_mode"] == "dataset_analysis"
        assert data["confidence"] == 0.9
        assert "answer" in data

def test_2_insufficient_data():
    # Calling chat with a dataset that doesn't exist
    response = client.post("/api/copilot/chat", json={
        "message": "Analyze this",
        "dataset_id": "non_existent_dataset"
    })
    assert response.status_code == 200
    data = response.json()
    assert data["response_mode"] == "insufficient_data"
    assert "not enough verified information" in data["answer"].lower()

def test_3_plain_text_normalization(test_dataset):
    with patch('exceptionos.ai.provider.MockAIProvider.generate', side_effect=mock_generate_plaintext):
        os.environ["AI_PROVIDER"] = "mock"
        response = client.post("/api/copilot/chat", json={
            "message": "Analyze this",
            "dataset_id": test_dataset.id
        })
        assert response.status_code == 200
        data = response.json()
        assert data["answer"] == "This is just some text the AI generated instead of JSON."
        assert data["confidence"] == 0.3

def test_4_missing_fields(test_dataset):
    with patch('exceptionos.ai.provider.MockAIProvider.generate', side_effect=mock_generate_malformed):
        os.environ["AI_PROVIDER"] = "mock"
        response = client.post("/api/copilot/chat", json={
            "message": "Analyze this",
            "dataset_id": test_dataset.id
        })
        # This will fail Pydantic validation and raise 400 because normalize won't fix it if it's not a single "error" key
        assert response.status_code == 400
        assert "Validation Failed" in response.json()["detail"]

def test_5_provider_failure(test_dataset):
    with patch('exceptionos.ai.provider.MockAIProvider.generate', side_effect=mock_generate_provider_failure):
        os.environ["AI_PROVIDER"] = "mock"
        response = client.post("/api/copilot/chat", json={
            "message": "Analyze this",
            "dataset_id": test_dataset.id
        })
        assert response.status_code == 503
        assert "temporarily unavailable" in response.json()["detail"]

def test_6_general_chat():
    with patch('exceptionos.ai.provider.MockAIProvider.generate', side_effect=mock_generate_valid):
        os.environ["AI_PROVIDER"] = "mock"
        response = client.post("/api/copilot/chat", json={
            "message": "What can you do?",
            # dataset_id omitted
        })
        assert response.status_code == 200
        data = response.json()
        assert data["response_mode"] == "general"

def test_7_dataset_analysis(test_dataset):
    with patch('exceptionos.ai.provider.MockAIProvider.generate', side_effect=mock_generate_valid):
        os.environ["AI_PROVIDER"] = "mock"
        response = client.post("/api/copilot/chat", json={
            "message": "Analyze",
            "dataset_id": test_dataset.id
        })
        assert response.status_code == 200
        data = response.json()
        assert data["response_mode"] == "dataset_analysis"

from exceptionos.ai.guardrails import normalize_ai_response

def test_8_error_response_is_normalized():
    raw = {
        "error": "Insufficient data to answer the question."
    }

    result = normalize_ai_response(raw)

    assert result["answer"]
    assert result["verified_facts"] == []
    assert result["recommendations"]
    assert result["confidence"] == 0.0
    assert result["sources"] == []
    assert result["response_mode"] == "insufficient_data"
