"""Deterministic Root Cause Selector for ExceptionOS."""
from dataclasses import dataclass, field
from typing import List, Optional

from exceptionos.pipeline.unified import UnifiedCase
from exceptionos.pipeline.timeline import EvidenceTimeline
from exceptionos.intelligence.hypothesis import Hypothesis

@dataclass
class RootCauseDecision:
    root_cause: Optional[str]
    confidence_score: int
    status: str
    selected_hypothesis: Optional[Hypothesis]
    supporting_evidence: List[str] = field(default_factory=list)
    explanation: str = ""
    alternative_hypotheses: List[Hypothesis] = field(default_factory=list)
    requires_human_review: bool = False

def select_root_cause(
    case: UnifiedCase, 
    timeline: EvidenceTimeline, 
    hypotheses: List[Hypothesis]
) -> RootCauseDecision:
    """Deterministically selects the most probable root cause from a ranked list of hypotheses."""
    
    # Base case: NO_EXCEPTION
    if case.classification == "matched":
        return RootCauseDecision(
            root_cause=None,
            confidence_score=100,
            status="NO_EXCEPTION",
            selected_hypothesis=None,
            supporting_evidence=["All expected records exist and amounts/dates align perfectly."],
            explanation="This transaction is fully matched and settled. No exception exists."
        )

    # Base case: UNKNOWN / empty hypotheses
    if not hypotheses:
        return RootCauseDecision(
            root_cause="unknown",
            confidence_score=0,
            status="UNKNOWN",
            selected_hypothesis=None,
            supporting_evidence=["No hypotheses were generated by the intelligence engine."],
            explanation="The root cause is completely unknown.",
            requires_human_review=True
        )

    # Note: hypotheses are already sorted by confidence descending
    top = hypotheses[0]
    alternatives = hypotheses[1:]
    runner_up = alternatives[0] if alternatives else None
    
    # 1. Unknown Fallback
    if top.hypothesis_type == "unknown_discrepancy":
        return RootCauseDecision(
            root_cause=top.hypothesis_type,
            confidence_score=top.confidence_score,
            status="UNKNOWN",
            selected_hypothesis=top,
            supporting_evidence=top.evidence,
            explanation=top.explanation,
            alternative_hypotheses=alternatives,
            requires_human_review=True
        )

    # 2. Conflicting Evidence Check (Too close to call)
    if runner_up and (top.confidence_score - runner_up.confidence_score <= 10):
        return RootCauseDecision(
            root_cause="needs_review",
            confidence_score=top.confidence_score,
            status="NEEDS_REVIEW",
            selected_hypothesis=top,
            supporting_evidence=[
                f"Top hypothesis ({top.hypothesis_type}) scored {top.confidence_score}.",
                f"Runner-up hypothesis ({runner_up.hypothesis_type}) scored {runner_up.confidence_score}.",
                "The evidence gap is <= 10 points. Evidence is too close to confidently select one cause."
            ],
            explanation="Multiple hypotheses have strong conflicting evidence.",
            alternative_hypotheses=alternatives,
            requires_human_review=True
        )

    # 3. Low Confidence Check
    if top.confidence_score < 60:
        return RootCauseDecision(
            root_cause="needs_review",
            confidence_score=top.confidence_score,
            status="NEEDS_REVIEW",
            selected_hypothesis=top,
            supporting_evidence=top.evidence + [f"The confidence score ({top.confidence_score}) is below the minimum threshold (60) for automatic assignment."],
            explanation="The leading hypothesis does not have enough evidence to be selected automatically.",
            alternative_hypotheses=alternatives,
            requires_human_review=True
        )

    # 4. Confirmed Status
    if top.confidence_score >= 85:
        return RootCauseDecision(
            root_cause=top.hypothesis_type,
            confidence_score=top.confidence_score,
            status="CONFIRMED",
            selected_hypothesis=top,
            supporting_evidence=top.evidence,
            explanation=top.explanation,
            alternative_hypotheses=alternatives,
            requires_human_review=False
        )

    # 5. Probable Status
    return RootCauseDecision(
        root_cause=top.hypothesis_type,
        confidence_score=top.confidence_score,
        status="PROBABLE",
        selected_hypothesis=top,
        supporting_evidence=top.evidence,
        explanation=top.explanation,
        alternative_hypotheses=alternatives,
        requires_human_review=False
    )
